@base_url = http://localhost/user
@username = testuser22
@admin_username = admin1
@admin_password = pass123
@password = testpassword2
@email = test@email.com
@role = user
@username = 93aca379-26b1-4b31-9451-988c6e13bedf
@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMzIyNjAwNiwianRpIjoiOThmYjdjNzMtMDkzOS00NWE5LTk3YTktYTlhNDBhZjQ3Y2U5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImFkbWluMSIsIm5iZiI6MTczMzIyNjAwNiwiY3NyZiI6IjBlMWM3NjI1LTQ0NTItNGQ0My04MzQxLTlkOTQ3NjYwN2RkMiIsImV4cCI6MTczMzIyOTYwNiwicm9sZSI6ImFkbWluIn0.CDrzxVZtHpO-rfLhG7Q0CYGhb1-Y6c4CAy7fyieHptE


# @name HelloWorld
GET {{base_url}}/ HTTP/1.1
###

#TODO: missing endpoints:
#"/update-name"
#"/update-password"
#"/update-email"
#"/password-recovery"
#"/update-user/<int:username>"

# @name insertAdmin
POST {{base_url}}/insert-admin HTTP/1.1
###

# @name getUsers
GET {{base_url}}/users HTTP/1.1
Authorization: Bearer {{JWT}}
###

# @name makeUser
POST {{base_url}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "username"  : "testdev",
    "password"  : "developer",
    "email"     : "minmail@gmail.com",
    "role"      : "developer"
}
###


# @name login
POST {{base_url}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}
###

## @name loginAdmin
POST {{base_url}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "{{admin_username}}",
    "password": "{{admin_password}}"
}
###

###

# @name deleteUser
DELETE {{base_url}}/user HTTP/1.1
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
    "username": "{{username}}"
}
###