apiVersion: v1
kind: Service
metadata:
  name: service-ctf
  namespace: project
spec:
  type: NodePort
  selector:
    app: ctf
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
    nodePort: 30081