apiVersion: v1
kind: Service
metadata:
  name: service-comp
  namespace: project
spec:
  type: NodePort
  selector:
    app: comp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30080