apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  type: NodePort  # Change to LoadBalancer if running on a cloud provider
  selector:
    app: istio-ingressgateway
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
